;;;; cl-user-funcs.lisp

(in-package #:mnas-dim-value )

(defun import-symbols ()
  (import 'mnas-dim-value:quantity-interactive (find-package :cl-user))
  (import 'mnas-dim-value:qi (find-package :cl-user))
  (import 'mnas-dim-value:quantity-from-string (find-package :cl-user))
  (import 'mnas-dim-value:quantity (find-package :cl-user))
  (import 'mnas-dim-value:vd (find-package :cl-user))
  (import 'mnas-dim-value:^ (find-package :cl-user))
  (import 'mnas-dim-value:vd* (find-package :cl-user))
  (import 'mnas-dim-value:vd/ (find-package :cl-user))
  (import 'mnas-dim-value:vd+ (find-package :cl-user))
  (import 'mnas-dim-value:vd- (find-package :cl-user))
  (import 'mnas-dim-value:vd-expt (find-package :cl-user))
  (import 'mnas-dim-value:|m| (find-package :cl-user))
  (import 'mnas-dim-value:|kg| (find-package :cl-user))
  (import 'mnas-dim-value:|s| (find-package :cl-user))
  (import 'mnas-dim-value:|A| (find-package :cl-user))
  (import 'mnas-dim-value:|K| (find-package :cl-user))
  (import 'mnas-dim-value:|cd| (find-package :cl-user))
  (import 'mnas-dim-value:|mol| (find-package :cl-user))
  (import 'mnas-dim-value:|rad| (find-package :cl-user))
  (import 'mnas-dim-value:|sr| (find-package :cl-user))
  (import 'mnas-dim-value:|Hz| (find-package :cl-user))
  (import 'mnas-dim-value:|N| (find-package :cl-user))
  (import 'mnas-dim-value:|Pa| (find-package :cl-user))
  (import 'mnas-dim-value:|J| (find-package :cl-user))
  (import 'mnas-dim-value:|W| (find-package :cl-user))
  (import 'mnas-dim-value:|C| (find-package :cl-user))
  (import 'mnas-dim-value:|V| (find-package :cl-user))
  (import 'mnas-dim-value:|F| (find-package :cl-user))
  (import 'mnas-dim-value:|Ω| (find-package :cl-user))
  (import 'mnas-dim-value:|S| (find-package :cl-user))
  (import 'mnas-dim-value:|Wb| (find-package :cl-user))
  (import 'mnas-dim-value:|Τ| (find-package :cl-user))
  (import 'mnas-dim-value:|H| (find-package :cl-user))
  (import 'mnas-dim-value:|lm| (find-package :cl-user))
  (import 'mnas-dim-value:|lx| (find-package :cl-user))
  (import 'mnas-dim-value:|Bq| (find-package :cl-user))
  (import 'mnas-dim-value:|Gy| (find-package :cl-user))
  (import 'mnas-dim-value:|Sv| (find-package :cl-user))
  (import 'mnas-dim-value:|kat| (find-package :cl-user))
  )
