* [0/7] ToDo
1. [ ] (defgeneric unit-name (x stream) - зачем здесь параметр
   stream. Возможно лучше возвращать строку.
2. [ ] Диалоговая программа ввода данных
3. [ ] Консольная интерактивная программа с возможностями:
   - [ ] присвоения значения переменным;
   - [ ] загрузки выражений из файла (человеко-читаемого);
   - [ ] выгрузка выражений в файл (человеко-читаемый);
   - [ ] написания функций.
4. [ ] Печать класса <vd>
   - [ ] Ввести переключатели:
     - [ ] Вывода телесных углов
       - sr - стерадиан
       - 
   - [ ] Печать класса <vd> с диапазоном значений от 0.1 до 1000;
   - [ ] Печать класса <vd> в html формат;
   - [ ] Печать в виде суммы величин для величины типа
     - время c -> (+ д ч мин с) => 15 д 9 ч 25 мин 50.25 с;
5. [ ] Добавить документацию
   - [ ] к функциям;
6. [ ] Пакеты mnas-dim-value/ht-en; mnas-dim-value/ht-ru - перенести
   схожий код в пакет mnas-dim-value/ht.
7. [ ] Определения для величин производных, кратных, внесистемных
   относительно основных единиц системы SI лучше задать в виде
   функциональной зависимости. Лучше задать две функции:
   - для преобразования численного значения единицы (производной,
     кратной, внесистемной) численное значение основной единицы
     системы SI;
   - для преобразования основной единицы системы SI ;

* [20/20] DoNe
1. [X] Изменить поведение vd-convert для обеспечения считывания
   градусной меры:
   - [X] :dms - например: 9°07′06.56″;
   - [X] :dm  - например: 9°07.1093′;
   - [X] :s   - например: 9.118489°;

2. [X] Печать класса <vd>
   - [X] Ввести переключатели:
     - [X] *language* - язык вывода
       - [X] en
       - [X] ru
       - [X] uk
     - [X] *angle* - вывода угловых величин
       - :rad  - вывод в радианах (круг=2π);
       - :grad - вывод в градах (круг=400 град);
       - :rot  - вывод в оборотах;
       - :dms  - например: 9°07′06.56″;
       - :dm   - например: 9°07.1093′;
       - :d    - например: 9.118489°;
       - :ms   - например: 547′06.56″;
       - :m    - например: 547.1093′;
       - :s    - например: 32826.56″."
     - [X] *a-units* - точность представления угловых величин
     - [X] *units* - Количество значащих цифр в представлении величин
       за исключением угловых.
     - [X] *time* - формат вывода интервала времени:
       - [X] :year - год = 365.25 суток;
       - [X] :mon  - месяц = (/ 365.25 12) суток;
       - [X] :d    - сутки;
       - [X] :h    - час;
       - [X] :m    - минута;
       - [X] :s    - секунда.
       - [X] :dhms - сутки, часы, минуты секунды;
       - [X] :hms  - часы, минуты, секунды;
       - [X] :ms   - минуты, секунды.
   - [X] Вывода угловых величин
     - [X] Написать функцию angle-string для преобразования радиан в
       строку в виде градусов минут секунд;

3. [X] Определить функции:
   - [X] vd~pow
   - [X] vd~root
   - [X] vd~exp
   - [X] vd~expt
   - [X] vd~ln
   - [X] vd~log
   - [X] vd~sin
   - [X] vd~cos
   - [X] vd~tan
   - [X] vd~asin
   - [X] vd~acos
   - [X] vd~atan
   - [X] vd~sinh
   - [X] vd~cosh
   - [X] vd~tanh
   - [X] vd~asinh
   - [X] vd~acosh
   - [X] vd~atanh
   - [X] vd~abs
   - [X] vd~equal
   - [X] vd~equalp

4. [X] Переименовать таблицы:
   - [X] *table-1-the-seven-defining-constants-of-the-si-and-the-seven-corresponding-units-they-define* -> *table-1-en*
   - [X] *nd-table-2-si-base-units* -> *table-2-en*
   - [X] *nd-table-4-the-22-si-units-with-special-names-and-symbols* -> *table-4-en*
   - [X] *nd-table-5-examples-of-coherent-derived-units-in-the-si-expressed-in-terms-of-base-units* -> *table-5-en*
   - [X] *nd-table-6-examples-of-si-coherent-derived-units-whose-names-and-symbols-include-si-coherent-derived-units-with-special-names-and-symbols* -> *table-6-en*
   - [X] *table-7-si-prefixes* -> *table-7-en*
   - [X] *nd-table-8-non-si-units-accepted-for-use-with-the-si-units* -> *table-8-en*
5. [X]  Для класса <nd> исключить суффиксы связанные с яыком, оставив
   только международное обозначение. Добавить символ языка для,
   которого действует это определение.
   
   - quantity-name-en -> quantity-name
   - quantity-name-ru - исключить 
   - unit-name-en -> unit-name
   - unit-symbol-en -> unit-symbol
   #+begin_src lisp
     (defclass <nd> ()
       ((quantity-name-en :accessor <nd>-quantity-name-en  :initarg :quantity-name-en :initform "" :documentation "Наименование величины английское. Например: length")
        (quantity-name-ru :accessor <nd>-quantity-name-ru  :initarg :quantity-name-ru :initform "" :documentation "Наименование величины русское. Например: длина")
        (unit-name-en     :accessor <nd>-unit-name-en      :initarg :unit-name-en     :initform "" :documentation "Наименование единицы английское. Например: metre") 
        (unit-name-ru     :accessor <nd>-unit-name-ru      :initarg :unit-name-ru     :initform "" :documentation "Наименование единицы русское. Например: метр") 
        (unit-symbol-en   :accessor <nd>-unit-symbol-en    :initarg :unit-symbol-en   :initform "" :documentation "Обозначение единицы английское. Например: m")
        (unit-symbol-ru   :accessor <nd>-unit-symbol-ru    :initarg :unit-symbol-ru   :initform "" :documentation "Обозначение единицы русское. Например: м")
        (dimension-symbol :accessor <nd>-dimension-symbol  :initarg :dimension-symbol :initform "" :documentation "Символ размерности. Например: L")
        (value            :accessor <nd>-value             :initarg :value            :initform 1  :documentation "Значение, выраженное в единицах СИ. Например: (vd 1 :m 1)")
        (coeff            :accessor <nd>-coeff             :initarg :coeff :initform '((-24 24))   :documentation "Список диапазонов разрешенных степеней множителей для данной величины системы СИ"))
       (:documentation "Величина с размерностью. Данный класс служит исключительно для
     удобства в определении чисел с размерностью."))

   #+end_src

6. [X] Вынести файлы с таблицами в отдельную систему. В определении
   таблиц исключить размерности типа |m|, |s| и т.д.
7. [X] Создать новую ветку git - dev.
8. [X] Разобраться с безразмерными величинами. На настоящий момент
   образуются безразмерные величины с множительными
   приставками. Например Gul, Mul, kul=1000 ul. Лучше, чтобы
   образовывалась только одна безразмерная единица без множительной
   приставки.
9. [X] Переименовать класс vd -> <vd>.
10. [X] Переименовать класс nd -> <nd>.
11. [X] Переименовать аксессор vd-val -> <vd>-val. 
12. [X] Переименовать аксессор <vd>-dims -> <vd>-dims.
13. [X] Добавить имена типов размерностей для данных, содержащихся в переменных
14. [X] Импортировать функции vd*, vd/, vd+, vd- в пакет :cl-user.
15. [X] Импортировать в пакет :cl-user значения размерностей, имеющих наименования.
16. [X] Исправить предупреждение в методе print-object ((x vd) o-s)
17. [X] Заменить defparameter на defvar в определении хеш таблиц
18. [X] Разбор выражения, заданного в виде строки
19. [X] Выбор множителей
    - [X] для таблицы 5;
    - [X] для таблицы 7.
20. [2/2] Добавить документацию
    - [X] подключить CODEX; 
    - [X] к классам;
21. [X] Печать класса vd с разделителями;
